-- Generated by scripts/generate-seed-sql.mjs. Idempotent: safe to re-run.
begin;

insert into public.organizations (slug, name) values ('baki-texniki-kolleci', 'Bakı Texniki Kolleci')
  on conflict (slug) do nothing;

insert into public.class_groups (organization_id, name, academic_year)
select id, '11A', '2026/2027' from public.organizations where slug = 'baki-texniki-kolleci'
  on conflict (organization_id, name) do nothing;

-- Pentestinqə giriş
insert into public.paths (slug, title, description, category, status, order_index) values
  ('red-team-path', 'Red Team Path', 'Red Team Path kurikulumu', 'Hücum təhlükəsizliyi', 'PUBLISHED', 0)
  on conflict (slug) do update set status = 'PUBLISHED';

insert into public.learning_modules (path_id, slug, title, status, order_index)
select id, 'pentestinqe-giris', 'Pentestinqə giriş', 'PUBLISHED', 0 from public.paths where slug = 'red-team-path'
  on conflict (path_id, slug) do update set status = 'PUBLISHED';

insert into public.rooms (
  module_id, slug, title, short_title, eyebrow, description, category, type, difficulty,
  duration_label, points, accent, objectives, source_file, status, order_index, published_at
)
select m.id,
  'intro-to-pentesting', 'Pentestinqə giriş', 'Intro to Pentesting', 'Qırmızı komanda · Room 01', 'Pentestinqin əsaslarını, test növlərini, metodologiyanı və etik-hüquqi sərhədləri addım-addım öyrən.',
  'Hücum təhlükəsizliyi', 'WALKTHROUGH'::public.room_type, 'BEGINNER'::public.difficulty,
  '45–60 dəq', 500, 'GREEN'::public.content_accent,
  array['Pentestinqi oxşar təhlükəsizlik yanaşmalarından fərqləndirmək', 'Black, White və Grey Box test növlərini tanımaq', 'Standart pentestinq metodologiyasını ardıcıllıqla izah etmək', 'Scope, RoE və yazılı icazənin vacibliyini anlamaq']::text[], 'intro_to_pentesting.md', 'PUBLISHED', 0, now()
from public.learning_modules m
join public.paths p on p.id = m.path_id and p.slug = 'red-team-path'
where m.slug = 'pentestinqe-giris'
  on conflict (slug) do update set
    title = excluded.title, description = excluded.description, objectives = excluded.objectives,
    points = excluded.points, status = 'PUBLISHED';

delete from public.tasks where room_id = (select id from public.rooms where slug = 'intro-to-pentesting');

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 1, 'Pentestinq nədir?', '8 dəq', 100, '[{"body":"Penetration testing — sistem, şəbəkə və ya tətbiqdəki zəiflikləri real hücumçu kimi düşünərək, ancaq əvvəlcədən verilmiş icazə və razılaşdırılmış sərhədlər daxilində aşkarlamaq prosesidir."},{"heading":"Məqsəd sadəcə zəiflik tapmaq deyil","body":"Pentester tapıntının real riskini göstərir, mümkün təsiri sübut edir və düzəliş üçün konkret tövsiyə hazırlayır. Hücumçudan əsas fərqi məqsəd deyil, hər şeydən əvvəl yazılı icazə və hüquqi çərçivədir."},{"heading":"Sadə analogiya","body":"Bank seyfinin davamlılığını yoxlamaq üçün peşəkar mütəxəssisə onu sınaqdan keçirməyə icazə verir. Mütəxəssis heç nə oğurlamır; haradan və necə daxil olmağın mümkün olduğunu hesabatda göstərir."}]'::jsonb
  from public.rooms where slug = 'intro-to-pentesting'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Pentesteri real hücumçudan fərqləndirən əsas amil hansıdır?', 'Pentester yalnız yazılı icazə və razılaşdırılmış scope daxilində işləyir. Eyni texniki addımlar icazəsiz olduqda qanunsuz sayılır.', 100
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Bilik səviyyəsi', false),
  (1, 'İcazə və hüquqi razılaşma', true),
  (2, 'İstifadə etdiyi alətlər', false),
  (3, 'İş saatları', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 2, 'Oxşar anlayışlar', '10 dəq', 100, '[{"body":"Təhlükəsizlik sahəsində eyni görünən yanaşmaların məqsədi və dərinliyi fərqlidir. Düzgün termin seçimi gözləntiləri və nəticəni aydınlaşdırır.","bullets":["Vulnerability Assessment — məlum zəiflikləri aşkarlayır, adətən istismar etmir.","Penetration Test — zəifliyin real təsirini nəzarətli şəkildə sübut edir.","Red Teaming — insan, proses və texnologiyanın bütöv müdafiəsini sınayır.","Bug Bounty — müstəqil tədqiqatçıların tapıntıya görə mükafat aldığı proqramdır."]},{"heading":"Yadda saxla","body":"Zəiflik qiymətləndirməsi xəritəni çəkir; pentestinq seçilmiş yolların həqiqətən keçilə bildiyini yoxlayır."}]'::jsonb
  from public.rooms where slug = 'intro-to-pentesting'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Zəiflikləri siyahıya alır, lakin onları istismar etmir. Bu hansı prosesdir?', 'Vulnerability Assessment əsasən aşkarlama və prioritetləndirməyə fokuslanır; istismar onun əsas məqsədi deyil.', 100
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Red Teaming', false),
  (1, 'Bug Bounty', false),
  (2, 'Vulnerability Assessment', true),
  (3, 'Post-Exploitation', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 3, 'Black, White və Grey Box', '9 dəq', 100, '[{"body":"Testin tipi pentesterə əvvəlcədən verilən məlumatın həcminə görə seçilir.","bullets":["Black Box — daxili məlumat yoxdur; xarici hücumçu baxışını simulyasiya edir.","White Box — mənbə kodu, şəbəkə sxemi və hesablar daxil olmaqla tam məlumat verilir.","Grey Box — məhdud daxili məlumatla real kompromis olunmuş istifadəçi ssenarisi qurulur."]},{"heading":"Praktik seçim","body":"Daha az məlumat realizmi artırsa da vaxtı uzadır. Daha çox məlumat isə ayrılmış müddətdə daha dərin yoxlama aparmağa imkan verir."}]'::jsonb
  from public.rooms where slug = 'intro-to-pentesting'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Mənbə kodu və şəbəkə sxemi verilən test hansı növdür?', 'White Box yanaşmasında pentester tam daxili məlumata malik olur və daha dərin yoxlama aparır.', 100
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Black Box', false),
  (1, 'White Box', true),
  (2, 'Grey Box', false),
  (3, 'Blind Box', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 4, 'Pentestinq metodologiyası', '12 dəq', 100, '[{"body":"Peşəkar pentest xaotik deyil. İş PTES kimi çərçivələrə uyğun, izlənilə bilən mərhələlərlə aparılır.","bullets":["01 · Pre-engagement — məqsəd, scope və Rules of Engagement","02 · Reconnaissance — hədəf haqqında məlumat toplama","03 · Scanning & Enumeration — port, servis və versiyaları müəyyən etmə","04 · Exploitation — seçilmiş zəifliyin təsirini sübut etmə","05 · Post-Exploitation — girişin təsirini və əhatəsini qiymətləndirmə","06 · Reporting — riskləri və düzəliş addımlarını sənədləşdirmə"]},{"heading":"Proses iterativdir","body":"Yeni tapıntı komandanı əvvəlki mərhələyə qaytara bilər. Ən vacib nəticə isə təşkilatın istifadə edə biləcəyi aydın hesabatdır."}]'::jsonb
  from public.rooms where slug = 'intro-to-pentesting'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Nmap ilə açıq portları müəyyən etmək hansı mərhələyə aiddir?', 'Portların, servislərin və versiyaların texniki aşkarlanması Scanning & Enumeration mərhələsidir.', 100
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Pre-engagement', false),
  (1, 'Scanning & Enumeration', true),
  (2, 'Post-Exploitation', false),
  (3, 'Reporting', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 5, 'Hüquqi və etik çərçivə', '10 dəq', 100, '[{"body":"Pentestinq yalnız yazılı icazə əsasında qanunidir. Yaxşı niyyət texniki fəaliyyəti avtomatik olaraq qanuni etmir.","bullets":["Scope — test edilə bilən sistem, domen və IP sərhədlərini göstərir.","Rules of Engagement — vaxtı, icazəli üsulları və əlaqə qaydasını müəyyən edir.","Authorization letter — mütəxəssisin razılaşdırılmış işi gördüyünü təsdiqləyir."]},{"heading":"Əsas prinsip","body":"Sadəcə bacardığın üçün etməyə haqqın yoxdur. Etik hakerlik bacarıq qədər məsuliyyət və etimaddır."}]'::jsonb
  from public.rooms where slug = 'intro-to-pentesting'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Test saatlarını və icazə verilən üsulları hansı sənəd tənzimləyir?', 'Rules of Engagement testin necə aparılacağını, məhdudiyyətləri və kritik hal zamanı əlaqəni dəqiqləşdirir.', 100
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Risk Register', false),
  (1, 'Rules of Engagement', true),
  (2, 'Vulnerability Report', false),
  (3, 'Service Catalogue', false)
) as opt(order_index, label, is_correct);

-- GRC əsasları
insert into public.paths (slug, title, description, category, status, order_index) values
  ('blue-team-path', 'Blue Team Path', 'Blue Team Path kurikulumu', 'GRC', 'PUBLISHED', 1)
  on conflict (slug) do update set status = 'PUBLISHED';

insert into public.learning_modules (path_id, slug, title, status, order_index)
select id, 'tehlukesizlik-idareetmesi', 'Təhlükəsizlik idarəetməsi', 'PUBLISHED', 0 from public.paths where slug = 'blue-team-path'
  on conflict (path_id, slug) do update set status = 'PUBLISHED';

insert into public.rooms (
  module_id, slug, title, short_title, eyebrow, description, category, type, difficulty,
  duration_label, points, accent, objectives, source_file, status, order_index, published_at
)
select m.id,
  'grc-foundations', 'GRC əsasları', 'Introduction to GRC', 'Müdafiə və idarəetmə · Room 02', 'Governance, Risk və Compliance sütunlarının təşkilatın kibertəhlükəsizlik qərarlarını necə birləşdirdiyini öyrən.',
  'GRC', 'ANALYSIS'::public.room_type, 'BEGINNER'::public.difficulty,
  '55–70 dəq', 650, 'RED'::public.content_accent,
  array['Governance, Risk və Compliance anlayışlarını izah etmək', 'Üç sütunun bir-birini necə tamamladığını anlamaq', 'Risk cavab strategiyalarını real ssenariyə tətbiq etmək', 'Əsas GRC çərçivələrini və yetkinlik pillələrini tanımaq']::text[], 'Introduction_to_GRC_Detailed.md', 'PUBLISHED', 1, now()
from public.learning_modules m
join public.paths p on p.id = m.path_id and p.slug = 'blue-team-path'
where m.slug = 'tehlukesizlik-idareetmesi'
  on conflict (slug) do update set
    title = excluded.title, description = excluded.description, objectives = excluded.objectives,
    points = excluded.points, status = 'PUBLISHED';

delete from public.tasks where room_id = (select id from public.rooms where slug = 'grc-foundations');

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 1, 'GRC nədir?', '9 dəq', 130, '[{"body":"GRC — Governance, Risk və Compliance funksiyalarını vahid strategiyada birləşdirən idarəetmə yanaşmasıdır. Məqsəd təşkilatın hədəflərinə etibarlı çatması, qeyri-müəyyənliyi idarə etməsi və dürüst fəaliyyət göstərməsidir."},{"heading":"Üç əsas sual","body":"GRC rəhbərliyə qərar vermək üçün ortaq dil yaradır.","bullets":["Governance: Doğru işi, doğru qaydada görürükmü?","Risk: Hədəfimizə çatmağa nə mane ola bilər?","Compliance: Bizə tətbiq olunan qaydalara əməl edirikmi?"]}]'::jsonb
  from public.rooms where slug = 'grc-foundations'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'GRC-ni ən düzgün təsvir edən fikir hansıdır?', 'GRC ayrı bir alət və ya şöbə deyil; idarəetmə, risk və uyğunluğu ortaq məqsəd ətrafında birləşdirən sistemli yanaşmadır.', 130
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Yalnız audit proqramıdır', false),
  (1, 'Üç funksiyanı birləşdirən idarəetmə yanaşmasıdır', true),
  (2, 'Yalnız qanunların siyahısıdır', false),
  (3, 'Texniki zəiflik skaneridir', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 2, 'Üç sütun birlikdə', '11 dəq', 130, '[{"body":"Governance istiqaməti və məsuliyyəti müəyyən edir. Risk Management qeyri-müəyyənliyi ölçür. Compliance isə qərarların qanun, standart və daxili siyasətlərə uyğunluğunu yoxlayır."},{"heading":"Silo probleminin həlli","body":"Funksiyalar ayrı işlədikdə auditlər təkrarlanır, risk dili fərqlənir və sahibsiz boşluqlar yaranır. İnteqrasiya vahid məlumat mənbəyi, ortaq prioritet və aydın hesabat yaradır."}]'::jsonb
  from public.rooms where slug = 'grc-foundations'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Governance-in əsas rolu hansıdır?', 'Governance təşkilatın istiqamətini, qərar mexanizmini və kimin nəyə cavabdeh olduğunu müəyyən edir.', 130
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Yalnız texniki nəzarət qurmaq', false),
  (1, 'İstiqamət, struktur və hesabatlılıq yaratmaq', true),
  (2, 'Bütün riskləri sıfırlamaq', false),
  (3, 'Yalnız cərimələri hesablamaq', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 3, 'Risk dövrü və cavablar', '14 dəq', 130, '[{"body":"Risk idarəetməsi riskin aşkarlanması, qiymətləndirilməsi, prioritetləndirilməsi, cavab seçimi, nəzarətlərin tətbiqi və davamlı monitorinq dövrüdür.","bullets":["Avoid — risk yaradan fəaliyyəti dayandır.","Mitigate — ehtimalı və ya təsiri nəzarətlə azalt.","Transfer — maliyyə yükünün bir hissəsini üçüncü tərəfə ötür.","Accept — əsaslandırılmış şəkildə riski qəbul et."]},{"heading":"Nəzarət növləri","body":"Preventive nəzarət hadisəni qabaqlayır, detective nəzarət hadisəni aşkarlayır, corrective nəzarət isə normal fəaliyyəti bərpa edir."}]'::jsonb
  from public.rooms where slug = 'grc-foundations'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'MFA tətbiq etməklə hesab oğurluğu ehtimalını azaltmaq hansı cavabdır?', 'MFA fəaliyyəti dayandırmır; təhlükənin uğur ehtimalını nəzarət vasitəsilə azaltdığı üçün mitigate strategiyasıdır.', 130
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Avoid', false),
  (1, 'Mitigate', true),
  (2, 'Transfer', false),
  (3, 'Accept', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 4, 'Çərçivələr və standartlar', '13 dəq', 130, '[{"body":"Təşkilatlar ehtiyaclarına görə bir neçə çərçivəni birlikdə istifadə edir. Hər çərçivə fərqli idarəetmə problemini strukturlaşdırır.","bullets":["COSO ERM — müəssisə risklərini strategiya ilə birləşdirir.","ISO 31000 — ümumi risk idarəetmə prinsipləri verir.","ISO 27001 — informasiya təhlükəsizliyi idarəetmə sistemini qurur.","NIST CSF — Identify, Protect, Detect, Respond, Recover funksiyalarını təqdim edir.","COBIT — İT idarəetməsi və nəzarətlərinə fokuslanır."]},{"heading":"Bir ölçü hamıya uyğun deyil","body":"Orta ölçülü şirkət ümumi risk üçün COSO, informasiya təhlükəsizliyi üçün ISO 27001 və kibertəhlükəsizlik təcrübələri üçün NIST CSF seçə bilər."}]'::jsonb
  from public.rooms where slug = 'grc-foundations'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'İnformasiya təhlükəsizliyi idarəetmə sisteminə fokuslanan standart hansıdır?', 'ISO 27001 təşkilatda Information Security Management System (ISMS) qurmaq üçün tələblər verir.', 130
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'ISO 27001', true),
  (1, 'COSO ERM', false),
  (2, 'ISO 31000', false),
  (3, 'ITIL', false)
) as opt(order_index, label, is_correct);

with new_task as (
  insert into public.tasks (room_id, order_index, title, duration_label, points, sections)
  select id, 5, 'GRC yetkinliyi və ssenari', '12 dəq', 130, '[{"body":"GRC yetkinliyi Fragmented səviyyədən Optimized səviyyəyə qədər inkişaf edir. Yetkin təşkilatda risk qərarları strategiyaya inteqrasiya olunur, göstəricilər ölçülür və nəzarətlər davamlı təkmilləşdirilir.","bullets":["Level 1 — Fragmented: reaktiv və ayrı-ayrı proseslər","Level 2 — Defined: əsas siyasətlər mövcuddur","Level 3 — Integrated: ortaq risk dili və koordinasiya","Level 4 — Managed: KPI/KRI ilə ölçülən proseslər","Level 5 — Optimized: proaktiv analitika və davamlı inkişaf"]},{"heading":"Ssenari","body":"Vendor yoxlanmadan geniş sistem girişi alır və məlumat sızması baş verir. Governance siyasət boşluğu, risk qiymətləndirilməsinin aparılmaması və compliance sübutunun olmaması bir hadisədə kəsişir."}]'::jsonb
  from public.rooms where slug = 'grc-foundations'
  returning id
), new_question as (
  insert into public.questions (task_id, order_index, type, prompt, explanation, points)
  select id, 1, 'SINGLE_CHOICE', 'Ortaq risk dili və koordinasiya hansı yetkinlik səviyyəsinə uyğundur?', 'Integrated səviyyədə governance, risk və compliance komandaları ortaq taksonomiya və məlumatla koordinasiyalı işləyir.', 130
  from new_task
  returning id
)
insert into public.question_options (question_id, order_index, label, is_correct)
select new_question.id, opt.order_index, opt.label, opt.is_correct
from new_question, (values
  (0, 'Fragmented', false),
  (1, 'Defined', false),
  (2, 'Integrated', true),
  (3, 'Optimized', false)
) as opt(order_index, label, is_correct);

commit;
