// AUTO-GENERATED from AgshinMirzalizada/holbertonschool-cyber_security (rooms/).
// Room prose lives in ./holberton/<sourceFile>; regenerate rather than hand-editing.

export interface HolbertonRoom {
  slug: string;
  title: string;
  shortTitle: string;
  eyebrow: string;
  description: string;
  category: string;
  type: 'WALKTHROUGH' | 'CHALLENGE' | 'ANALYSIS';
  difficulty: 'BEGINNER' | 'INTERMEDIATE' | 'ADVANCED';
  durationLabel: string;
  points: number;
  accent: 'RED' | 'GREEN';
  objectives: string[];
  pathSlug: string;
  pathTitle: string;
  moduleSlug: string;
  moduleTitle: string;
  sourceFile: string;
  orderIndex: number;
}

export const holbertonRooms: readonly HolbertonRoom[] = [
  {
    slug: "esas-pentesting-aletleri",
    title: "Əsas Pentesting Alətlərinə Baxış",
    shortTitle: "Əsas Pentesting Alətlərinə Baxış",
    eyebrow: "Red Team · Pentesting Toolkit & Mühit",
    description: "Nmap, Burp Suite, Metasploit, Wireshark, John the Ripper kimi alətlərin qısa tanıtımı — hər birinin hansı mərhələdə istifadə olunduğu, dərinə getmədən ümumi xəritə.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "BEGINNER",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Pentest mərhələləri (recon → enumeration → exploitation → post-exploitation) ilə alətlərin uyğunluğunu bilmək", "Nmap, Burp Suite, Metasploit, Wireshark, John the Ripper-in rolunu bir cümlə ilə izah edə bilmək", "Hansı vəzifə üçün hansı alətin seçiləcəyinə qərar vermək", "Alətin bilik əvəzetmədiyi prinsipini dərk etmək"],
    pathSlug: "kibertehlukesizlik-2-red-team-fundamentals",
    pathTitle: "Red Team təməlləri",
    moduleSlug: "2.2-toolkit-environment",
    moduleTitle: "Pentesting Toolkit & Mühit",
    sourceFile: "esas-pentesting-aletleri.md",
    orderIndex: 0,
  },
  {
    slug: "kali-linux-qurulumu",
    title: "Kali Linux Qurulumu",
    shortTitle: "Kali Linux Qurulumu",
    eyebrow: "Red Team · Pentesting Toolkit & Mühit",
    description: "Kali Linux nədir, niyə pentesting üçün seçilir, VirtualBox/VMware üzərində qurulması, ilkin konfiqurasiya (update/upgrade), əsas qovluq strukturu.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "BEGINNER",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Kali Linux-un nə olduğunu və niyə industry standard hesab edildiyini izah edə bilmək", "VirtualBox və ya VMware üzərində Kali virtual maşınını qurmaq", "Sistemi ilkin konfiqurasiya etmək (update/upgrade, snapshot almaq)", "Kali-nin əsas qovluq strukturunu tanımaq və terminalda rahat hərəkət etmək"],
    pathSlug: "kibertehlukesizlik-2-red-team-fundamentals",
    pathTitle: "Red Team təməlləri",
    moduleSlug: "2.2-toolkit-environment",
    moduleTitle: "Pentesting Toolkit & Mühit",
    sourceFile: "kali-linux-qurulumu.md",
    orderIndex: 1,
  },
  {
    slug: "vpn-ile-laba-qosulma",
    title: "VPN ilə Lab-a Qoşulma",
    shortTitle: "VPN ilə Lab-a Qoşulma",
    eyebrow: "Red Team · Pentesting Toolkit & Mühit",
    description: "OpenVPN konfiqurasiyası, .ovpn faylının istifadəsi, lab mühitinə qoşulma addımları, tez-tez rast gəlinən qoşulma problemləri.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "BEGINNER",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["VPN-in lab mühitlərində nə üçün istifadə edildiyini izah etmək", ".ovpn faylını qəbul edib OpenVPN ilə qoşulmaq", "Qoşulmanın uğurlunu yoxlamaq (IP yoxlaması, ping, interfeys)", "Ümumi qoşulma xətalarını diaqnoz etmək və həll etmək"],
    pathSlug: "kibertehlukesizlik-2-red-team-fundamentals",
    pathTitle: "Red Team təməlləri",
    moduleSlug: "2.2-toolkit-environment",
    moduleTitle: "Pentesting Toolkit & Mühit",
    sourceFile: "vpn-ile-laba-qosulma.md",
    orderIndex: 2,
  },
  {
    slug: "aktiv-recon-nmap",
    title: "Aktiv Recon — Nmap",
    shortTitle: "Aktiv Recon",
    eyebrow: "Red Team · Recon & Enumeration",
    description: "Nmap-ın əsas skan növləri (SYN scan, TCP connect, UDP scan), port state-ləri (open/closed/filtered), əsas flag-lar (-sV, -sC, -A, -p-).",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "BEGINNER",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Aktiv recon-un passiv recon-dan fərqini və görünənliyini (hədəf loglarında iz) anlamaq", "Nmap-ın üç əsas skan növünü (SYN, TCP connect, UDP) və fərqlərini bilmək", "Port state-lərini (open/closed/filtered) düzgün şərh etmək", "`-sV`, `-sC`, `-A`, `-p-` flag-lərini məqsədə uyğun istifadə etmək"],
    pathSlug: "kibertehlukesizlik-2-red-team-fundamentals",
    pathTitle: "Red Team təməlləri",
    moduleSlug: "2.3-recon-enumeration",
    moduleTitle: "Recon & Enumeration",
    sourceFile: "aktiv-recon-nmap.md",
    orderIndex: 3,
  },
  {
    slug: "passiv-recon-osint",
    title: "Passiv Recon (OSINT Əsasları)",
    shortTitle: "Passiv Recon",
    eyebrow: "Red Team · Recon & Enumeration",
    description: "Passiv recon nədir, hədəflə birbaşa əlaqəyə girmədən məlumat toplama, Google Dorking, WHOIS, subdomain aşkarlama alətləri (crt.sh və s.).",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "BEGINNER",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Passiv recon ilə aktiv recon arasındakı fərqi izah etmək", "Google Dorking ilə axtarış mühərribindən \"kəşfiyyat aləti\" kimi istifadə etmək", "WHOIS vasitəsilə domain məlumatlarını əldə etmək", "crt.sh kimi alətlərlə subdomain aşkarlamaq"],
    pathSlug: "kibertehlukesizlik-2-red-team-fundamentals",
    pathTitle: "Red Team təməlləri",
    moduleSlug: "2.3-recon-enumeration",
    moduleTitle: "Recon & Enumeration",
    sourceFile: "passiv-recon-osint.md",
    orderIndex: 4,
  },
  {
    slug: "servis-enumeration",
    title: "Servis Enumeration",
    shortTitle: "Servis Enumeration",
    eyebrow: "Red Team · Recon & Enumeration",
    description: "Banner grabbing, versiya aşkarlama, açıq servislərdən (SMB, FTP, HTTP) əlavə məlumat çıxarma texnikaları.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "BEGINNER",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Enumeration-un recon-dan fərqini və pentest axınındakı yerini izah etmək", "Banner grabbing texnikası ilə servis məlumatı əldə etmək", "SMB, FTP və HTTP servis-lərində əlavə məlumat çıxarma üsullarını bilmək", "Hər servis üçün \"hansı məlumat axtarılır\" düşünmə modelini qurmaq"],
    pathSlug: "kibertehlukesizlik-2-red-team-fundamentals",
    pathTitle: "Red Team təməlləri",
    moduleSlug: "2.3-recon-enumeration",
    moduleTitle: "Recon & Enumeration",
    sourceFile: "servis-enumeration.md",
    orderIndex: 5,
  },
  {
    slug: "http-https-derinden",
    title: "HTTP/HTTPS Dərindən",
    shortTitle: "HTTP/HTTPS Dərindən",
    eyebrow: "Red Team · Web Fundamentals",
    description: "HTTP request/response strukturu, metodlar (GET/POST/PUT/DELETE), header-lər, cookie/session, HTTPS-in TLS ilə necə işlədiyi.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["HTTP request/response strukturu və əsas metodları (GET/POST/PUT/DELETE) izah etmək", "Əsas header-lərin (Host, Content-Type, Cookie, Authorization) funksiyalarını bilmək", "Cookie və session mexanizminin necə işlədiyini başa düşmək", "HTTPS-in TLS handshake və şifrələmə ilə trafiki necə qoruduğunu izah etmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.1-web-fundamentals",
    moduleTitle: "Web Fundamentals",
    sourceFile: "http-https-derinden.md",
    orderIndex: 6,
  },
  {
    slug: "web-tetbiq-arxitekturasi",
    title: "Web Tətbiq Arxitekturası Əsasları",
    shortTitle: "Web Tətbiq Arxitekturası Əsasları",
    eyebrow: "Red Team · Web Fundamentals",
    description: "Frontend/backend/database ayrımı, client-server modeli, API-lərin rolu, tipik 3-qatlı arxitektura.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 480,
    accent: "RED",
    objectives: ["Frontend, backend və database qatlarının rol və məsuliyyətlərini ayırd etmək", "Client-server modelində məlumat axınını izləmək", "API anlayışını və REST-in əsas prinsiplərini izah etmək", "3-tier arxitekturanı reallıqda tanımaq və hər qatın hücum səthini müəyyən etmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.1-web-fundamentals",
    moduleTitle: "Web Fundamentals",
    sourceFile: "web-tetbiq-arxitekturasi.md",
    orderIndex: 7,
  },
  {
    slug: "broken-authentication",
    title: "Broken Authentication",
    shortTitle: "Broken Authentication",
    eyebrow: "Red Team · OWASP Top 10",
    description: "Zəif sessiya idarəetməsi, brute-force-a açıq login formaları, credential stuffing, MFA-nın rolu.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Autentifikasiya (auth) və avtorizasiyanın (access control) fərqini ayırd etmək", "Zəif sessiya idarəetməsinin klassik xətalarını sadalamaq", "Brute-force və credential stuffing hücumlarını və onlardan qorunmanı izah etmək", "MFA-nın təhlükəsizlik dəyərini və bypass variantlarının konseptini bilmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "broken-authentication.md",
    orderIndex: 8,
  },
  {
    slug: "csrf",
    title: "CSRF",
    shortTitle: "CSRF",
    eyebrow: "Red Team · OWASP Top 10",
    description: "CSRF-in necə işlədiyi, istifadəçinin bilmədən icra etdiyi sorğu ssenarisi, CSRF token-in qorunma mexanizmi kimi rolu.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["CSRF-in işləmə prinsipini (browser-in cookie-ləri avtomatik göndərməsi) izah etmək", "Tipik CSRF ssenarisini (parol dəyişmə, email yeniləmə) qurmaq", "CSRF-in Şərtlərini və hansı sorğuların qorunmalı olduğunu müəyyən etmək", "CSRF token, SameSite cookie və digər müdafiə təbəqələrini izah etmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "csrf.md",
    orderIndex: 9,
  },
  {
    slug: "file-upload-zeiflikleri",
    title: "File Upload Zəiflikləri",
    shortTitle: "File Upload Zəiflikləri",
    eyebrow: "Red Team · OWASP Top 10",
    description: "Fayl növü yoxlamasının bypass olunması, webshell yükləmə riski, düzgün fayl validasiyası prinsipləri.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Fayl yükləmə zəifliyinin RCE-yə necə çevrildiyini izah etmək", "Client-side və zəif server-side yoxlamaların bypass üsullarını bilmək", "Webshell-in nə olduğunu və necə işlədiyini konseptual başa düşmək", "Düzgün fayl validasiyasının çoxtəbəqəli prinsiplərini sadalamaq"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "file-upload-zeiflikleri.md",
    orderIndex: 10,
  },
  {
    slug: "idor",
    title: "IDOR (Insecure Direct Object Reference)",
    shortTitle: "IDOR",
    eyebrow: "Red Team · OWASP Top 10",
    description: "IDOR-un tərifi, URL/parametr manipulyasiyası ilə başqasının məlumatına giriş nümunəsi, access control-un rolu.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["IDOR-un tərifini və authentication/authorization fərqinə yerləşdirmək", "URL və parametr manipulyasiyası ilə IDOR tapmağın metodologiyasını tətbiq etmək", "IDOR-un API, cookie və fayl yükləmə kimi müxtəlif səthlərini tanımaq", "Server tərəfli access control-un düzgün qurulmasını izah etmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "idor.md",
    orderIndex: 11,
  },
  {
    slug: "security-misconfiguration",
    title: "Security Misconfiguration",
    shortTitle: "Security Misconfiguration",
    eyebrow: "Red Team · OWASP Top 10",
    description: "Default credential-lar, açıq debug rejimləri, lazımsız açıq servislər, düzgün konfiqurasiyanın vacibliyi.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Default credential-ların riskini və yoxlama metodunu bilmək", "Açıq debug rejimlərinin hansı məlumatları sızdırdığını izah etmək", "Lazımsız açıq servislərin və directory listing-in hücum səthinə təsirini qiymətləndirmək", "Düzgün konfiqurasiya praktikalarını (hardening, environment ayrımı) sadalamaq"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "security-misconfiguration.md",
    orderIndex: 12,
  },
  {
    slug: "sql-injection",
    title: "SQL Injection",
    shortTitle: "SQL Injection",
    eyebrow: "Red Team · OWASP Top 10",
    description: "SQLi-nin necə işlədiyi, in-band/blind/union-based növləri, sadə zəif kodda nümunə, niyə parametrized query həll yoludur.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["SQLi-nin yaranma səbəbini (string concatenation) kod səviyyəsində izah etmək", "In-band (error/union-based), blind və time-based SQLi növlərini ayırd etmək", "Sadə input manipulyasiyası ilə sorğu məntiqinin necə dəyişdiyini izləmək", "Parametrized query (prepared statement) niyə təməl həll yolu olduğunu izah etmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "sql-injection.md",
    orderIndex: 13,
  },
  {
    slug: "xss",
    title: "Cross-Site Scripting (XSS)",
    shortTitle: "Cross-Site Scripting",
    eyebrow: "Red Team · OWASP Top 10",
    description: "Stored/Reflected/DOM-based XSS fərqləri, sadə payload nümunəsi (izah səviyyəsində), niyə input sanitization vacibdir.",
    category: "Red Team",
    type: "CHALLENGE",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["XSS-in işləmə prinsipini (input-un HTML/JS kontekstinə çıxması) izah etmək", "Stored, Reflected və DOM-based növlərini ayırd etmək", "Sadə payload strukturlarını və session oğurluğu ssenarisini konseptual bilmək", "Output encoding, sanitization və CSP-nin müdafiə rollarını izah etmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.2-owasp-top-10",
    moduleTitle: "OWASP Top 10",
    sourceFile: "xss.md",
    orderIndex: 14,
  },
  {
    slug: "avtomatlasdirilmis-skan-aletleri",
    title: "Avtomatlaşdırılmış Skan Alətləri",
    shortTitle: "Avtomatlaşdırılmış Skan Alətləri",
    eyebrow: "Red Team · Web Exploitation Alətləri",
    description: "OWASP ZAP-ın əsas funksiyaları, avtomatik skanların üstünlükləri/məhdudiyyətləri, manual test ilə niyə birgə istifadə olunmalıdır.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["OWASP ZAP-ın əsas funksiyalarını (spider, active scan, proxy) tanımaq", "Avtomatik skanın üstünlüklərini və real dəyərini müəyyən etmək", "Skanerin məhdudiyyətlərini (business logic, blind zones, false positives) izah etmək", "Skan + manual test kombinasiyasının düzgün metodologiyasını qurmaq"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.3-web-exploitation-tools",
    moduleTitle: "Web Exploitation Alətləri",
    sourceFile: "avtomatlasdirilmis-skan-aletleri.md",
    orderIndex: 15,
  },
  {
    slug: "burp-suite-esaslari",
    title: "Burp Suite Əsasları",
    shortTitle: "Burp Suite Əsasları",
    eyebrow: "Red Team · Web Exploitation Alətləri",
    description: "Burp Suite-in interfeysi, Proxy tab-ı, Intercept mexanizmi, Repeater-in sadə istifadəsi.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Burp Suite-in interfeys və modul strukturunu tanımaq", "Proxy + browser konfiqurasiyası ilə trafiyi tutmağı tətbiq etmək", "Intercept mexanizmi ilə sorğuları saxlamaq və dəyişməyi bacarmaq", "Repeater ilə sorğu təkrarı və analiz aparmağı öyrənmək"],
    pathSlug: "kibertehlukesizlik-3-web-app-hacking",
    pathTitle: "Veb tətbiq təhlükəsizliyi",
    moduleSlug: "3.3-web-exploitation-tools",
    moduleTitle: "Web Exploitation Alətləri",
    sourceFile: "burp-suite-esaslari.md",
    orderIndex: 16,
  },
  {
    slug: "metasploit-esaslari",
    title: "Metasploit Framework Əsasları",
    shortTitle: "Metasploit Framework Əsasları",
    eyebrow: "Red Team · Network Exploitation",
    description: "Metasploit-in strukturu (exploit/payload/auxiliary), msfconsole-un əsas komandaları, search/use/set/run axını konseptual səviyyədə.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Metasploit-in strukturunu (exploit, payload, auxiliary, post modulları) izah etmək", "msfconsole-un əsas komandaları ilə işləmək", "Search → use → set → exploit/run axınını tətbiq etmək", "Meterpreter-in nə olduğunu və niyə güclü olduğunu bilmək"],
    pathSlug: "kibertehlukesizlik-4-network-security",
    pathTitle: "Şəbəkə təhlükəsizliyi",
    moduleSlug: "4.1-network-exploitation",
    moduleTitle: "Network Exploitation",
    sourceFile: "metasploit-esaslari.md",
    orderIndex: 17,
  },
  {
    slug: "umumi-servislerin-istismari",
    title: "Ümumi Servislərin İstismarı (FTP, SMB, SSH)",
    shortTitle: "Ümumi Servislərin İstismarı",
    eyebrow: "Red Team · Network Exploitation",
    description: "Anonymous FTP girişi, SMB null session, zəif SSH konfiqurasiyası kimi tipik zəifliklər, hər biri üçün konseptual nümunə.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Anonymous FTP girişindən istismara gedən yolu izləmək", "SMB null session və bilinən zəifliklərin (konseptual) istismarını anlamaq", "Zəif SSH konfiqurasiyasının (parol auth, zəif açarlar) istismarını bilmək", "Hər servisin müdafiə konfiqurasiyasını sadalamaq"],
    pathSlug: "kibertehlukesizlik-4-network-security",
    pathTitle: "Şəbəkə təhlükəsizliyi",
    moduleSlug: "4.1-network-exploitation",
    moduleTitle: "Network Exploitation",
    sourceFile: "umumi-servislerin-istismari.md",
    orderIndex: 18,
  },
  {
    slug: "manual-zeiflik-dogrulamasi",
    title: "Manual Zəiflik Doğrulaması",
    shortTitle: "Manual Zəiflik Doğrulaması",
    eyebrow: "Red Team · Vulnerability Assessment",
    description: "Avtomatik skanerin false positive verə bilməsi, niyə manual doğrulama vacibdir, sadə doğrulama metodologiyası.",
    category: "Red Team",
    type: "ANALYSIS",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["False positive və false negative anlayışlarını izah etmək", "Manual doğrulamanın zəruriliyini (qərar keyfiyyəti baxımından) əsaslandırmaq", "Versiya-əsaslı və davranış-əsaslı doğrulama fərqini bilmək", "Sadə doğrulama metodologiyasını (mərhələlərlə) tətbiq etmək"],
    pathSlug: "kibertehlukesizlik-4-network-security",
    pathTitle: "Şəbəkə təhlükəsizliyi",
    moduleSlug: "4.2-vulnerability-assessment",
    moduleTitle: "Vulnerability Assessment",
    sourceFile: "manual-zeiflik-dogrulamasi.md",
    orderIndex: 19,
  },
  {
    slug: "zeiflik-skanlamasi",
    title: "Zəiflik Skanlaması (Nessus/OpenVAS)",
    shortTitle: "Zəiflik Skanlaması",
    eyebrow: "Red Team · Vulnerability Assessment",
    description: "Vulnerability scanner-lərin iş prinsipi, CVE/CVSS anlayışları, skan nəticələrinin oxunması.",
    category: "Red Team",
    type: "ANALYSIS",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Vulnerability scanner-in iş prinsipini (port skan → servis identifikasiya → plug-in yoxlamaları) izah etmək", "Nessus və OpenVAS alətlərinin quraşdırma və skan axınını bilmək", "CVE və CVSS anlayışlarını izah etmək", "Skan hesabatını oxuyub tapıntıları qiymətləndirmək"],
    pathSlug: "kibertehlukesizlik-4-network-security",
    pathTitle: "Şəbəkə təhlükəsizliyi",
    moduleSlug: "4.2-vulnerability-assessment",
    moduleTitle: "Vulnerability Assessment",
    sourceFile: "zeiflik-skanlamasi.md",
    orderIndex: 20,
  },
  {
    slug: "ad-enumeration",
    title: "AD Enumeration (BloodHound, PowerView)",
    shortTitle: "AD Enumeration",
    eyebrow: "Red Team · AD Fundamentals",
    description: "BloodHound-un attack path vizuallaşdırması, PowerView ilə əsas enumeration komandaları (konseptual səviyyədə).",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["AD enumeration-un məqsədini və toplanan məlumat növlərini izah etmək", "PowerView-un əsas komandalarını (konseptual) bilmək", "BloodHound-un toplama (SharpHound) və analiz axınını anlamaq", "Attack path anlayışını və klassik qısa yolları tanımaq"],
    pathSlug: "kibertehlukesizlik-5-active-directory",
    pathTitle: "Active Directory təhlükəsizliyi",
    moduleSlug: "5.1-ad-fundamentals",
    moduleTitle: "AD Fundamentals",
    sourceFile: "ad-enumeration.md",
    orderIndex: 21,
  },
  {
    slug: "ad-strukturu-komponentleri",
    title: "AD Strukturu & Komponentləri",
    shortTitle: "AD Strukturu & Komponentləri",
    eyebrow: "Red Team · AD Fundamentals",
    description: "Domain, Domain Controller, OU, Group Policy, Forest/Tree anlayışları, AD-nin kurumsal mühitdə rolu.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["AD-nin nə olduğunu və korporativ mühitdə rolunu izah etmək", "Domain, Domain Controller, OU, Group Policy anlayışlarını ayırd etmək", "Forest/Tree/Domain iyerarxiyasını izah etmək", "AD obyektlərini (user, group, computer) və autentifikasiya axınını konseptual bilmək"],
    pathSlug: "kibertehlukesizlik-5-active-directory",
    pathTitle: "Active Directory təhlükəsizliyi",
    moduleSlug: "5.1-ad-fundamentals",
    moduleTitle: "AD Fundamentals",
    sourceFile: "ad-strukturu-komponentleri.md",
    orderIndex: 22,
  },
  {
    slug: "ad-lateral-movement",
    title: "AD-də Lateral Movement",
    shortTitle: "AD-də Lateral Movement",
    eyebrow: "Red Team · AD Hücum Texnikaları",
    description: "Bir sistemdən digərinə keçid konsepti, WMI/PsExec kimi üsulların qısa icmalı, niyə segmentasiya müdafiə tədbiridir.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Lateral movement konseptini və onun AD hücum zəncirindəki rolunu izah etmək", "WMI, PsExec, WinRM, RDP kimi hərəkət üsullarını müqayisə etmək", "Hərəkətin yaratdığı izləri (log/event) bilmək", "Seqmentasiya və digər müdafiə tədbirlərinin əhəmiyyətini izah etmək"],
    pathSlug: "kibertehlukesizlik-5-active-directory",
    pathTitle: "Active Directory təhlükəsizliyi",
    moduleSlug: "5.2-ad-attack-techniques",
    moduleTitle: "AD Hücum Texnikaları",
    sourceFile: "ad-lateral-movement.md",
    orderIndex: 23,
  },
  {
    slug: "kerberoasting",
    title: "Kerberoasting",
    shortTitle: "Kerberoasting",
    eyebrow: "Red Team · AD Hücum Texnikaları",
    description: "Kerberos autentifikasiyasının qısa izahı, service ticket-lərin necə tələb olunduğu, offline crack riski.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Kerberos TGT/TGS axınını xatırlamaq və Kerberoasting-in bu axındakı yerini göstərmək", "Service ticket-in offline crack imkanını izah etmək", "Hədəf seçim meyarlarını (SPN-li hesablar, parol gücü) bilmək", "Kerberoasting-ə qarşı müdafiə tədbirlərini sadalamaq"],
    pathSlug: "kibertehlukesizlik-5-active-directory",
    pathTitle: "Active Directory təhlükəsizliyi",
    moduleSlug: "5.2-ad-attack-techniques",
    moduleTitle: "AD Hücum Texnikaları",
    sourceFile: "kerberoasting.md",
    orderIndex: 24,
  },
  {
    slug: "pass-the-hash-ticket",
    title: "Pass-the-Hash / Pass-the-Ticket",
    shortTitle: "Pass-the-Hash / Pass-the-Ticket",
    eyebrow: "Red Team · AD Hücum Texnikaları",
    description: "Şifrəni bilmədən hash/ticket ilə autentifikasiya konsepti, niyə bu texnika bu qədər təhlükəlidir.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Parolun NTLM hash forması ilə avtorizasiyanın niyə mümkün olduğunu izah etmək", "Pass-the-Hash hücumunu alətlərlə (konseptual) tətbiq etmək", "Pass-the-Ticket və OverPass-the-Hash fərqlərini bilmək", "PtH/PtT-ə qarşı müdafiə təbəqələrini sadalamaq"],
    pathSlug: "kibertehlukesizlik-5-active-directory",
    pathTitle: "Active Directory təhlükəsizliyi",
    moduleSlug: "5.2-ad-attack-techniques",
    moduleTitle: "AD Hücum Texnikaları",
    sourceFile: "pass-the-hash-ticket.md",
    orderIndex: 25,
  },
  {
    slug: "linux-privesc-esaslar",
    title: "Linux PrivEsc — Əsaslar",
    shortTitle: "Linux PrivEsc",
    eyebrow: "Red Team · Linux PrivEsc",
    description: "Privilege escalation-ın niyə vacib olduğu, SUID/SGID, kernel exploit, cron job kimi ümumi vector-ların icmalı.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Privilege escalation-ın hücum zəncirindəki rolunu izah etmək", "SUID/SGID mexanizmini və onun istismar məntiqini başa düşmək", "Kernel exploit və cron job vector-larını konseptual bilmək", "Privesc axtarışının sistemli yanaşmasını (enum avtomatlaşdırması) qurmaq"],
    pathSlug: "kibertehlukesizlik-6-privilege-escalation",
    pathTitle: "Səlahiyyət yüksəltmə",
    moduleSlug: "6.1-linux-privesc",
    moduleTitle: "Linux PrivEsc",
    sourceFile: "linux-privesc-esaslar.md",
    orderIndex: 26,
  },
  {
    slug: "linux-privesc-praktiki",
    title: "Linux PrivEsc — Praktiki Texnikalar",
    shortTitle: "Linux PrivEsc",
    eyebrow: "Red Team · Linux PrivEsc",
    description: "sudo -l ilə icazə yoxlaması, yazıla bilən /etc/passwd, GTFOBins konsepti — konkret addım-addım nümunələr.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["`sudo -l` çıxışını oxumağı və icazələri istismar etməyi", "GTFOBins konseptini və istifadəsini tətbiq etmək", "Yazıla bilən `/etc/passwd` texnikasını addım-addım icra etmək", "Tapıntıdan istismara tam keçidi (enum → texnika → root) bacarmaq"],
    pathSlug: "kibertehlukesizlik-6-privilege-escalation",
    pathTitle: "Səlahiyyət yüksəltmə",
    moduleSlug: "6.1-linux-privesc",
    moduleTitle: "Linux PrivEsc",
    sourceFile: "linux-privesc-praktiki.md",
    orderIndex: 27,
  },
  {
    slug: "windows-privesc-esaslar",
    title: "Windows PrivEsc — Əsaslar",
    shortTitle: "Windows PrivEsc",
    eyebrow: "Red Team · Windows PrivEsc",
    description: "Windows icazə modeli, service misconfiguration, unquoted service path, AlwaysInstallElevated kimi vector-ların icmalı.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Windows icazə modelini (SID, token, integrity levels) izah etmək", "Service misconfiguration privesc-inin məntiqini başa düşmək", "Unquoted service path texnikasını izah etmək", "AlwaysInstallElevated və digər registry qapılarını tanımaq"],
    pathSlug: "kibertehlukesizlik-6-privilege-escalation",
    pathTitle: "Səlahiyyət yüksəltmə",
    moduleSlug: "6.2-windows-privesc",
    moduleTitle: "Windows PrivEsc",
    sourceFile: "windows-privesc-esaslar.md",
    orderIndex: 28,
  },
  {
    slug: "windows-privesc-praktiki",
    title: "Windows PrivEsc — Praktiki Texnikalar",
    shortTitle: "Windows PrivEsc",
    eyebrow: "Red Team · Windows PrivEsc",
    description: "WinPEAS konsepti, token impersonation qısa icmalı, konkret addım-addım nümunələr.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["winPEAS output-unu oxumaq və qapıları seçmək", "SeImpersonatePrivilege-ı JuicyPotato/PrintSpoofer ilə istismar etmək", "Servis registry qapısını addım-addım açmaq", "Webshell → SYSTEM tam zəncirini keçmək"],
    pathSlug: "kibertehlukesizlik-6-privilege-escalation",
    pathTitle: "Səlahiyyət yüksəltmə",
    moduleSlug: "6.2-windows-privesc",
    moduleTitle: "Windows PrivEsc",
    sourceFile: "windows-privesc-praktiki.md",
    orderIndex: 29,
  },
  {
    slug: "data-exfiltration",
    title: "Data Exfiltration Əsasları",
    shortTitle: "Data Exfiltration Əsasları",
    eyebrow: "Red Team · Post-Exploitation",
    description: "Məlumatın sistemdən çıxarılması üsulları (DNS tunneling, HTTP exfil) konseptual səviyyədə, aşkarlanma riskləri.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Exfiltration kanallarını (HTTP/S, DNS, cloud) və onların məntiqini izah etmək", "DNS tunneling-in necə işlədiyini konseptual bilmək", "Hər kanalın aşkarlanma əlamətlərini sadalamaq", "DLP və müdafiə tədbirlərinin əsaslarını bilmək"],
    pathSlug: "kibertehlukesizlik-7-post-exploitation",
    pathTitle: "Post-Exploitation əməliyyatları",
    moduleSlug: "7.1-post-exploitation",
    moduleTitle: "Post-Exploitation",
    sourceFile: "data-exfiltration.md",
    orderIndex: 30,
  },
  {
    slug: "persistence",
    title: "Persistence (Girişi Saxlama)",
    shortTitle: "Persistence",
    eyebrow: "Red Team · Post-Exploitation",
    description: "Persistence-in məqsədi, cron job/scheduled task, startup entry kimi sadə üsulların konsepti.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Persistence-in məqsədini və hücum lifecycle-dəki yerini izah etmək", "Linux-da cron job/SSH açar persistence üsullarını bilmək", "Windows-da scheduled task/registry/startup üsullarını bilmək", "Hər üsulun aşkarlanma/təmizlənmə tərəfini anlamaq"],
    pathSlug: "kibertehlukesizlik-7-post-exploitation",
    pathTitle: "Post-Exploitation əməliyyatları",
    moduleSlug: "7.1-post-exploitation",
    moduleTitle: "Post-Exploitation",
    sourceFile: "persistence.md",
    orderIndex: 31,
  },
  {
    slug: "c2-frameworklerine-giris",
    title: "C2 Framework-lərinə Giriş",
    shortTitle: "C2 Framework-lərinə Giriş",
    eyebrow: "Red Team · Command & Control (C2)",
    description: "C2-nin məqsədi, beacon/agent konsepti, məşhur framework-lərin (Cobalt Strike, Sliver) qısa icmalı.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["C2-nin məqsədini və əsas komponentlərini izah etmək", "Beacon/agent konseptini və kommunikasiya modellərini bilmək", "Məşhur framework-ləri (Cobalt Strike, Sliver, Mythic) müqayisə etmək", "C2 траfikinin aşkarlanması və müdafiə perspektivini anlamaq"],
    pathSlug: "kibertehlukesizlik-7-post-exploitation",
    pathTitle: "Post-Exploitation əməliyyatları",
    moduleSlug: "7.2-c2",
    moduleTitle: "Command & Control (C2)",
    sourceFile: "c2-frameworklerine-giris.md",
    orderIndex: 32,
  },
  {
    slug: "av-edr-evasion-esaslar",
    title: "AV/EDR Evasion Əsasları",
    shortTitle: "AV/EDR Evasion Əsasları",
    eyebrow: "Red Team · Evasion",
    description: "Signature-based aşkarlamanın necə işlədiyi, obfuscation konsepti, evasion-un etik sərhədləri.",
    category: "Red Team",
    type: "WALKTHROUGH",
    difficulty: "ADVANCED",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Signature-based və behavior-based aşdarlamanın fərqini izah etmək", "Obfuscation/packing/in-memory icra konseptlərini bilmək", "EDR-ın həllərini (hook, callback, telemetry) konseptual anlamaq", "Evasion biliklərinin etik istifadə sərhədlərini müəyyən etmək"],
    pathSlug: "kibertehlukesizlik-7-post-exploitation",
    pathTitle: "Post-Exploitation əməliyyatları",
    moduleSlug: "7.3-evasion",
    moduleTitle: "Evasion",
    sourceFile: "av-edr-evasion-esaslar.md",
    orderIndex: 33,
  },
  {
    slug: "pentest-hesabati-yazmaq",
    title: "Pentest Hesabatı Yazmaq",
    shortTitle: "Pentest Hesabatı Yazmaq",
    eyebrow: "Red Team · Professional Reporting",
    description: "Executive Summary, Technical Findings, Risk Rating, Remediation bölmələrinin strukturu, yaxşı hesabatın xüsusiyyətləri.",
    category: "Red Team",
    type: "ANALYSIS",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Hesabatın əsas strukturu və hər bölmənin auditoriyasını izah etmək", "Executive Summary-ni texnik dildən necə ayırmağı bilmək", "Tapıntının (finding) tam strukturunu yazmaq", "Yaxşı hesabatın keyfiyyət meyarlarını sadalamaq"],
    pathSlug: "kibertehlukesizlik-8-reporting-capstone",
    pathTitle: "Hesabatlıq və Capstone",
    moduleSlug: "8.1-professional-reporting",
    moduleTitle: "Professional Reporting",
    sourceFile: "pentest-hesabati-yazmaq.md",
    orderIndex: 34,
  },
  {
    slug: "risk-qiymetlendirmesi-cvss",
    title: "Risk Qiymətləndirməsi (CVSS)",
    shortTitle: "Risk Qiymətləndirməsi",
    eyebrow: "Red Team · Professional Reporting",
    description: "CVSS skorlama sisteminin əsas komponentləri (Attack Vector, Complexity, Impact), Critical/High/Medium/Low kateqoriyaları.",
    category: "Red Team",
    type: "ANALYSIS",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["CVSS-in əsas metrik qruplarını və hər metrikin mənasını izah etmək", "Vektor sətrini (məs. `AV:N/AC:L/PR:N/UI:N`) oxumaq və qurmaq", "Severity kateqoriyalarını və onların hesabat diliğini bilmək", "Skorun kontekstlə şərhi (CVSS-in məhdudiyyətləri) bacarmaq"],
    pathSlug: "kibertehlukesizlik-8-reporting-capstone",
    pathTitle: "Hesabatlıq və Capstone",
    moduleSlug: "8.1-professional-reporting",
    moduleTitle: "Professional Reporting",
    sourceFile: "risk-qiymetlendirmesi-cvss.md",
    orderIndex: 35,
  },
  {
    slug: "ucdan-uca-simulyasiya",
    title: "Tam Ssenari — Uçdan-uca Simulyasiya",
    shortTitle: "Tam Ssenari",
    eyebrow: "Red Team · Capstone",
    description: "Recon-dan reporting-ə qədər bütün mərhələləri birləşdirən yekun ssenari icmalı — bu room digərlərindən fərqli, daha çox tətbiq yönümlü olmalıdır.",
    category: "Red Team",
    type: "ANALYSIS",
    difficulty: "INTERMEDIATE",
    durationLabel: "45–60 dəq",
    points: 600,
    accent: "RED",
    objectives: ["Bütün pentest mərhələlərini (recon → reporting) vahid ssenaridə birləşdirmək", "Hər mərhələnin nəticəsinin növbəti mərhələyə \"xammal\" olduğunu görmək", "Kill chain modeli üzrə hücumu izləmək və izah etmək", "Tam hesabat (executive + technical) yazmağı tətbiq etmək"],
    pathSlug: "kibertehlukesizlik-8-reporting-capstone",
    pathTitle: "Hesabatlıq və Capstone",
    moduleSlug: "8.2-capstone",
    moduleTitle: "Capstone",
    sourceFile: "ucdan-uca-simulyasiya.md",
    orderIndex: 36,
  },
];
